### ISSUE TITLE
Bitfinex Reconnect Order Update Issue

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#1018]
So when trading on Bitfinex, sometimes there will be a random disconnect and the bot reconnects fine.
However, orders no longer properly register on the server side.

Web UI shows orders, but quotes stay at 0/0/0.
Some digging with --debug-orders shows this:
02/14 17:05:39.546863 GW BITFINEX Warrrrning: CURL recv Error: Failed sending data to the peer.
02/14 17:05:40.506855 GW BITFINEX Quoting state changed to DISCONNECTED.
02/14 17:05:40.507010 GW BITFINEX WS Disconnected, reconnecting in 7s..
02/14 17:05:47.769692 QE Warrrrning: Unable to calculate quote, missing market data.
02/14 17:05:47.810478 GW BITFINEX Quoting state changed to CONNECTED.
02/14 17:05:47.810556 GW BITFINEX WS Streaming wallet and orders OK 0:"auth".
02/14 17:05:47.810941 GW BITFINEX WS Streaming channel 188:trades.
02/14 17:05:48.393761 GW BITFINEX WS Streaming channel 157007:book.
02/14 17:07:59.507446 DEBUG OG  replace 7981870066::39568697695 [1]: 24.00000000 XRP at price 0.00003121 BTC.
02/14 17:08:36.343216 DEBUG OG  replace 7981870066::39568697695 [1]: 24.00000000 XRP at price 0.00003120 BTC.
02/14 17:08:55.992559 DEBUG OG  replace 7981870066::39568697695 [1]: 24.00000000 XRP at price 0.00003121 BTC.
02/14 17:09:03.370281 DEBUG OG  replace 7981870066::39568697695 [1]: 24.00000000 XRP at price 0.00003120 BTC.
02/14 17:09:08.507438 DEBUG OG  replace 7981870066::39568697695 [1]: 24.00000000 XRP at price 0.00003122 BTC.

When usually it should be a stream like this:
02/14 17:05:01.622751 DEBUG OG memory 2.
02/14 17:05:01.622771 DEBUG OG   purge  1834480321::39568697694 [2]: 24.00000000 XRP at price 0.00003120 BTC.
02/14 17:05:01.622788 DEBUG OG memory 1.
02/14 17:05:01.683819 DEBUG OG   saved  7981870066:: [0]: 24.00000000 XRP at price 0.00003120 BTC.
02/14 17:05:01.684953 DEBUG OG memory 2.
02/14 17:05:01.791596 DEBUG OG   reply  7981870066::39568697695 [1]: 24.00000000 XRP at price 0.00003120 BTC.
02/14 17:05:01.793376 DEBUG OG   saved  7981870066::39568697695 [1]: 24.00000000 XRP at price 0.00003120 BTC.
02/14 17:05:01.793409 DEBUG OG memory 2.

**Comment by MiningInMySleep** [comment]
Update: This same issue happened without even being disconnected. This time it's only for bids. Constant replace attempts without response from server. Asks are going through and getting a response without issue. Confirmed only asks showing up on actual exchange, while K interface shows nothing wrong.

**Comment by MiningInMySleep** [comment]
Update 2: It seems that when the disconnect happens, the current order is cancelled, but the bot still thinks it's there so it tries to replace it constantly and never realizes that it needs to submit a new order.

**Comment by MiningInMySleep** [comment]
Update 3: Increasing lifetime seems to help not being disconnected, but still ends up happening. Would be best just to have the bot realize that the orders it is trying to update don't exist anymore.

**Comment by eniware-org** [comment]
I am experiencing the same issue. Do you consider the limits for API calls? I notice that if I perform more trades the disconnect happens less frequently. Reading https://docs.bitfinex.com/docs/getting-started#section-rate-limits and https://github.com/bitfinexcom/bitfinex-api-node#how-many-orders-can-i-send might help.

**Comment by MiningInMySleep** [comment]
I've tried changing the limits, but I honestly don't think it matters. The Bitfinex API just randomly disconnects and K doesn't realize that the order has been cancelled.

**Comment by cryp2owl** [comment]
Did you guys try it on other exchanges as well? I think Bittrex is far more open when it comes to bot trading. also Kucoin.

**Comment by eniware-org** [comment]
> 
> 
> I've tried changing the limits, but I honestly don't think it matters. The Bitfinex API just randomly disconnects and K doesn't realize that the order has been cancelled.

This was addressed to @ctubio

**Comment by eniware-org** [comment]
@ctubio, Can we expect any reaction on this issue from you?

**Comment by MiningInMySleep** [comment]
Bump @ctubio
The issue is still here and I have a feeling it's not on the BitFinex side. Can we please have this looked at?

**Comment by eniware-org** [comment]
+1
![image](https://user-images.githubusercontent.com/34030382/99405877-264af300-28e5-11eb-9b73-4aace3253351.png)

**Comment by ctubio** [comment]
thank you for the report, let me try to move my lazy ass

**Comment by MiningInMySleep** [comment]
To add to this, restarting the quoting engine will allow orders to be sent properly if the disconnect order bug happens.

**Comment by eniware-org** [comment]
https://github.com/bitfinexcom/bitfinex-api-node#order-creation-limits IS the reason. Which is not to say that the bot should not handle the situation better and restart the quoting engine automatically after a (5 minutes?) delay or at least display it in the QuoteStatus.

**Comment by MiningInMySleep** [comment]
> https://github.com/bitfinexcom/bitfinex-api-node#order-creation-limits IS the reason. Which is not to say that the bot should not handle the situation better and restart the quoting engine automatically after a (5 minutes?) delay or at least display it in the QuoteStatus. One shall take care to limit the frequency of sending orders in order to avoid the `ERR_RATE_LIMIT` response from the exchange, like for example via `lifetime` as @MiningInMySleep has done, but this is fairly crude.

Are you actually seeing the "ERR_RATE_LIMIT" response from the exchange? Do I need to enable one of the debug options to see it? I'm testing higher and higher lifetime settings (currently at 600) and still running into disconnects with error messages related to curl that end up with a broken quoting system upon reconnect.

**Comment by eniware-org** [comment]
lifetime=600 is 0.6s! I run on 1000-1200 and have pretty high trading volume, so I don't get disconnected. However, I get disconnected very occasionally (less than once per week) by Bitfinex (e.g. when high trading volume is present on the exchange) and the QE then is not restarted. It is definitely a shortcoming of the bot. 
 `--debug-secret` is what you need to debug the gateway.

**Comment by MiningInMySleep** [comment]
Running the latest commit with the WS checksum stuff and got this error looping since 2+ hours ago.
`02/05 14:26:45.209077 GW BITFINEX PING TRADE BUY  0.00020000 BTC at price 37009 USD (value 7 USD).
02/05 14:33:57.378914 GW BITFINEX Warrrrning: WS Error: book out of sync, checksums failed..
02/05 14:33:57.724107 GW BITFINEX Quoting state changed to DISCONNECTED.
02/05 14:33:57.724250 GW BITFINEX WS Disconnected, reconnecting in 7s..
02/05 14:34:04.788774 QE Warrrrning: Unable to calculate quote, missing market data.
02/05 14:34:04.788898 GW BITFINEX WS Info {"event":"info","platform":{"status":1},"serverId":"504ed088-3dfd-43bc-82a9-58f99b9e2791","version":2}.
02/05 14:34:04.817816 GW BITFINEX Quoting state changed to CONNECTED.
02/05 14:34:04.818713 GW BITFINEX WS Streaming wallet and orders OK 0:"auth".
02/05 14:34:04.821138 GW BITFINEX WS Streaming channel 42:trades.
02/05 14:34:05.724127 QE Warrrrning: Unable to calculate quote, missing market data.
02/05 14:34:05.764862 GW BITFINEX WS Streaming channel 278868:book.
02/05 14:53:37.319497 GW BITFINEX Warrrrning: WS Error: book out of sync, checksums failed..
02/05 14:53:37.724147 GW BITFINEX Quoting state changed to DISCONNECTED.
02/05 14:53:37.724254 GW BITFINEX WS Disconnected, reconnecting in 7s..
02/05 14:53:44.782687 QE Warrrrning: Unable to calculate quote, missing market data.
02/05 14:53:44.782849 GW BITFINEX WS Info {"event":"info","platform":{"status":1},"serverId":"8bcd723b-0986-4d12-bfcc-cf25cf7a64c0","version":2}.
02/05 14:53:44.815345 GW BITFINEX Quoting state changed to CONNECTED.
02/05 14:53:44.815413 GW BITFINEX WS Streaming wallet and orders OK 0:"auth".
02/05 14:53:44.823596 GW BITFINEX WS Streaming channel 71564:trades.
02/05 14:53:45.724110 QE Warrrrning: Unable to calculate quote, missing market data.
02/05 14:53:46.115041 GW BITFINEX WS Streaming channel 98971:book.
02/05 14:53:46.323113 GW BITFINEX Warrrrning: WS Error: book out of sync, checksums failed..
02/05 14:53:46.724094 GW BITFINEX Quoting state changed to DISCONNECTED.
02/05 14:53:46.724203 GW BITFINEX WS Disconnected, reconnecting in 7s..
02/05 14:53:53.787649 QE Warrrrning: Unable to calculate quote, missing market data.
02/05 14:53:53.787766 GW BITFINEX WS Info {"event":"info","platform":{"status":1},"serverId":"25dff4e7-aa0d-4318-9bcc-2abefc7b6342","version":2}.
02/05 14:53:53.816502 GW BITFINEX Quoting state changed to CONNECTED.
02/05 14:53:53.816568 GW BITFINEX WS Streaming wallet and orders OK 0:"auth".
02/05 14:53:53.820056 GW BITFINEX WS Streaming channel 436571:trades.
02/05 14:53:54.724116 QE Warrrrning: Unable to calculate quote, missing market data.
02/05 14:53:55.188563 GW BITFINEX WS Streaming channel 618450:book.
02/05 14:54:29.236475 GW BITFINEX Warrrrning: WS Error: book out of sync, checksums failed..
02/05 14:54:29.725321 GW BITFINEX Quoting state changed to DISCONNECTED.
02/05 14:54:29.725410 GW BITFINEX WS Disconnected, reconnecting in 7s..
02/05 14:54:36.853696 QE Warrrrning: Unable to calculate quote, missing market data.
02/05 14:54:36.853816 GW BITFINEX WS Info {"event":"info","platform":{"status":1},"serverId":"ee11be43-fa54-42f2-b7a2-e1365ed6d35f","version":2}.
02/05 14:54:36.880279 GW BITFINEX Quoting state changed to CONNECTED.
02/05 14:54:36.880353 GW BITFINEX WS Streaming wallet and orders OK 0:"auth".
02/05 14:54:36.905629 GW BITFINEX WS Streaming channel 1036:trades.
02/05 14:54:37.096445 GW BITFINEX WS Streaming channel 301649:book.
02/05 14:54:37.291780 GW BITFINEX Warrrrning: WS Error: book out of sync, checksums failed..
02/05 14:54:37.724126 GW BITFINEX Quoting state changed to DISCONNECTED.
02/05 14:54:37.724242 GW BITFINEX WS Disconnected, reconnecting in 7s..
02/05 14:54:44.823813 QE Warrrrning: Unable to calculate quote, missing market data.
02/05 14:54:44.824570 GW BITFINEX WS Info {"event":"info","platform":{"status":1},"serverId":"d3d88ff9-5013-41c0-9183-0601450a3c9a","version":2}.
02/05 14:54:44.851480 GW BITFINEX Quoting state changed to CONNECTED.
02/05 14:54:44.851559 GW BITFINEX WS Streaming wallet and orders OK 0:"auth".
02/05 14:54:44.855088 GW BITFINEX WS Streaming channel 33748:trades.
02/05 14:54:44.980688 GW BITFINEX WS Streaming channel 551878:book.
02/05 14:56:35.257562 GW BITFINEX Warrrrning: WS Error: book out of sync, checksums failed..
02/05 14:56:35.724126 GW BITFINEX Quoting state changed to DISCONNECTED.
02/05 14:56:35.724242 GW BITFINEX WS Disconnected, reconnecting in 7s..
02/05 14:56:42.787031 QE Warrrrning: Unable to calculate quote, missing market data.
`

**Comment by ctubio** [comment]
@MiningInMySleep are you using the linux-x86_64 build or another?

for the whole last day i had only 1 time the book out of sync, but yours seems out of sync right after the very first check on every new reconnection

let me rereview this checksums calcs while adding some debug lines when it gets out of sync; an also to ask for another snapshot of the book instead of disconnect for 7 seconds (on next commits)

:koala: thank you for your report''

**Comment by ctubio** [comment]
maaaybe meaaanwhile can you paste a first run with `--debug-secret` enabled? so i can see all communication between you and your endpoint and calc the checksum manually from it? (to see if you really are missing data or is my checksum calc that is the worst ever)

**Comment by MiningInMySleep** [comment]
What parts do you need? There's a lot of stuff here and you recommended against sharing --debug-secret output.

**Comment by ctubio** [comment]
i would need starting from the book subcription message like for example here is mine (if you dont place orders, in the middle only wallet messages are expected, so you can remove them if you want, they look like: `[0,"wu",["exchange","BTC",0.00112837,0,0.00112837,null,null]].`, with `wu` IDs):

```
02/05 13:23:19.043063 DEBUG BITFINEX <<< {"chanId":678632,"channel":"book","event":"subscribed","freq":"F0","len":"100","pair":"BTCUSD","prec":"P0","symbol":"tBTCUSD"}
02/05 13:23:19.043696 GW BITFINEX WS Streaming channel 678632:book.
02/05 13:23:19.044567 DEBUG BITFINEX <<< [678632,[[37931,5,1.63673436],[37930,2,0.747615],[37929,2,0.39599472],[37928,1,0.0264],[37926,1,0.527616],[37924,1,0.4846],[37922,1,0.5729],[37921,1,0.7375],[37919,4,0.00104172],[37918,6,0.12765423],[37917,4,0.07940258],[37916,4,0.19867772],[37915,7,1.66841672],[37914,4,0.00104172],[37913,3,0.00084172],[37912,6,0.20261875],[37911,6,0.10419575],[37910,2,0.00064172],[37909,6,1.63294561],[37908,7,1.6024805],[37907,6,0.26503472],[37906,4,1.97918172],[37905,7,0.58991542],[37904,3,0.00084172],[37903,8,0.54148486],[37902,3,0.00084314],[37901,8,25.18456179],[37900,6,2.01404314],[37899,8,0.16466324],[37898,4,1.33033925],[37897,4,0.00104314],[37896,6,0.26991419],[37895,5,0.26580718],[37894,6,0.33105304],[37893,4,0.00104314],[37892,4,0.33061914],[37891,4,0.50084314],[37890,5,0.0148134],[37889,5,0.05607632],[37888,5,0.44292958],[37887,5,0.39056564],[37886,4,0.00128628],[37885,5,0.34245147],[37884,5,0.08092688],[37883,8,4.44081661],[37882,5,0.19923461],[37881,4,0.00128461],[37880,2,0.00064314],[37879,6,0.13578461],[37878,7,1.19664999],[37877,7,0.61823085],[37876,4,0.40634461],[37875,7,5.27729393],[37874,3,0.00084314],[37873,3,0.00108461],[37872,5,0.08174461],[37871,4,0.00128461],[37870,5,0.17919461],[37869,4,0.01169553],[37868,6,1.24557462],[37867,4,0.00128461],[37866,5,0.00193049],[37865,5,0.86308461],[37864,5,0.55986938],[37863,4,0.00128461],[37862,4,0.0125913],[37861,3,0.00108461],[37860,8,5.96076702],[37859,6,0.77528461],[37858,3,0.00108461],[37857,4,0.00128461],[37856,3,0.00084314],[37855,5,0.50590512],[37854,4,0.02729083],[37853,7,3.55555964],[37852,5,4.2392361],[37851,6,25.00172775],[37850,4,0.03095906],[37849,5,1.05473326],[37848,4,0.00128461],[37847,3,0.00108461],[37846,5,0.00428461],[37845,7,5.27487143],[37844,3,0.00084314],[37843,4,1.98159121],[37842,4,0.00128461],[37841,6,2.19155144],[37840,4,0.00128461],[37839,4,0.01608461],[37838,5,5.00348333],[37837,5,0.00533492],[37836,5,0.00184808],[37835,5,0.97820659],[37834,4,0.00128461],[37833,5,0.00172775],[37832,2,0.00064314],[37831,5,1.98717544],[37830,9,6.34979707],[37829,6,0.6340923],[37828,3,0.00108461],[37932,4,-1.73675305],[37936,1,-0.0931582],[37940,2,-0.68877599],[37941,1,-1],[37945,2,-0.39569],[37946,1,-0.343],[37949,1,-0.10551751],[37950,1,-0.395712],[37952,1,-0.18845653],[37953,4,-0.5854378],[37954,3,-0.76172369],[37955,2,-0.357336],[37956,4,-2.22386779],[37957,4,-3.81129078],[37958,1,-0.1699],[37959,2,-0.49763278],[37960,3,-0.5865037],[37962,3,-1.31913],[37964,2,-0.75684194],[37965,1,-0.659603],[37967,1,-0.42871933],[37968,2,-0.86367863],[37969,1,-0.25563595],[37971,1,-0.07991666],[37975,3,-1.96384332],[37976,2,-2.10199978],[37978,1,-0.12868],[37979,2,-0.35720966],[37981,1,-0.1078],[37982,1,-0.49677736],[37983,2,-2.32029083],[37984,1,-0.5428143],[37985,1,-1.91690315],[37987,2,-2.27834],[37991,1,-0.2],[37992,1,-0.2097],[37993,3,-1.45743423],[37994,3,-5.03683566],[37995,1,-5],[37996,1,-0.1],[37998,2,-1.01538966],[37999,4,-5.74882423],[38000,2,-1.30279419],[38001,3,-3.15707056],[38002,1,-0.5008],[38006,1,-0.00040732],[38007,2,-0.00081272],[38008,3,-0.62178634],[38009,3,-0.00122004],[38010,3,-0.00122004],[38011,2,-0.00081272],[38012,3,-0.00122004],[38013,3,-0.00122004],[38014,3,-5.2731116],[38015,4,-0.07932423],[38016,3,-0.00122004],[38017,5,-0.9376097],[38018,2,-0.00081272],[38019,4,-0.76022004],[38020,3,-1.05419393],[38021,3,-0.00122004],[38022,1,-0.0004054],[38023,3,-0.00122004],[38024,4,-0.08007895],[38025,3,-0.00122004],[38026,2,-0.00081464],[38027,3,-0.00122004],[38028,3,-0.00122004],[38029,5,-5.27456993],[38030,4,-0.00227297],[38031,4,-0.00227297],[38032,3,-0.00186712],[38033,4,-5.00186565],[38034,4,-2.9988652],[38035,4,-0.00227252],[38036,6,-1.1886005],[38037,4,-1.08146565],[38038,4,-0.77805247],[38039,5,-1.05565181],[38040,4,-0.00206565],[38041,4,-0.00227252],[38042,3,-0.0012143],[38043,5,-0.39656792],[38044,4,-2.63821442],[38045,5,-2.63862006],[38046,7,-4.00504852],[38047,4,-0.00226792],[38048,3,-1.00080812],[38049,4,-0.00226792],[38050,3,-0.00186183],[38051,4,-0.00226792],[38052,5,-4.08797122],[38053,5,-0.4522654],[38054,4,-0.00226851],[38055,3,-0.00186164],[38056,3,-0.00186242],[38057,4,-0.0022702],[38058,6,-2.31564949],[38059,4,-0.02248249],[38060,4,-0.00226851]]].
02/05 13:23:19.227948 DEBUG BITFINEX <<< [678632,[38060,0,-1]].
02/05 13:23:19.228519 DEBUG BITFINEX <<< [678632,[37896,7,0.72890419]].
02/05 13:23:19.228912 DEBUG BITFINEX <<< [678632,[37894,7,0.45191304]].
02/05 13:23:19.229271 DEBUG BITFINEX <<< [678632,[37893,5,0.20408314]].
02/05 13:23:19.229609 DEBUG BITFINEX <<< [678632,[37889,6,0.13768632]].
02/05 13:23:19.229863 DEBUG BITFINEX <<< [678632,[37997,1,-0.35183569]].
02/05 13:23:19.230162 DEBUG BITFINEX <<< [678632,"cs",-1478989978].
02/05 13:23:19.428217 DEBUG BITFINEX <<< [678632,[37912,5,0.20104172]].
02/05 13:23:19.428804 DEBUG BITFINEX <<< [678632,[37911,6,0.10261855]].
02/05 13:23:19.429382 DEBUG BITFINEX <<< [678632,[37910,3,0.00379539]].
02/05 13:23:19.429792 DEBUG BITFINEX <<< [678632,[37905,6,0.52683472]].
02/05 13:23:19.430049 DEBUG BITFINEX <<< [678632,[37904,5,0.43354509]].
02/05 13:23:19.430303 DEBUG BITFINEX <<< [678632,[37901,7,25.08994074]].
02/05 13:23:19.430672 DEBUG BITFINEX <<< [678632,[37900,7,2.10865319]].
02/05 13:23:19.430945 DEBUG BITFINEX <<< [678632,"cs",1406002038].
02/05 13:23:19.631942 DEBUG BITFINEX <<< [678632,[37936,0,-1]].
02/05 13:23:19.632546 DEBUG BITFINEX <<< [678632,[38059,0,-1]].
02/05 13:23:19.633048 DEBUG BITFINEX <<< [678632,[37931,6,1.63703508]].
02/05 13:23:19.633380 DEBUG BITFINEX <<< [678632,[37929,1,0.395694]].
02/05 13:23:19.633665 DEBUG BITFINEX <<< [678632,[37912,6,0.20261855]].
02/05 13:23:19.633941 DEBUG BITFINEX <<< [678632,[37911,6,0.10419537]].
02/05 13:23:19.634248 DEBUG BITFINEX <<< [678632,[37910,2,0.00064172]].
02/05 13:23:19.634515 DEBUG BITFINEX <<< [678632,[37905,7,0.58990766]].
02/05 13:23:19.634788 DEBUG BITFINEX <<< [678632,[37904,4,0.37047172]].
02/05 13:23:19.635043 DEBUG BITFINEX <<< [678632,[37903,9,0.66870486]].
02/05 13:23:19.635293 DEBUG BITFINEX <<< [678632,[37901,8,25.18455014]].
02/05 13:23:19.635541 DEBUG BITFINEX <<< [678632,[37900,6,2.01404314]].
02/05 13:23:19.635810 DEBUG BITFINEX <<< [678632,[37932,4,-1.77464759]].
02/05 13:23:19.636066 DEBUG BITFINEX <<< [678632,[37933,1,-0.06210071]].
02/05 13:23:19.636318 DEBUG BITFINEX <<< [678632,[37937,1,-0.09315106]].
02/05 13:23:19.636571 DEBUG BITFINEX <<< [678632,[38048,4,-1.48080812]].
02/05 13:23:19.636838 DEBUG BITFINEX <<< [678632,"cs",9756862].
02/05 13:23:19.834571 DEBUG BITFINEX <<< [678632,[37937,0,-1]].
02/05 13:23:19.835421 DEBUG BITFINEX <<< [678632,[37930,1,0.527615]].
02/05 13:23:19.836161 DEBUG BITFINEX <<< [678632,[37911,5,0.10104172]].
02/05 13:23:19.836572 DEBUG BITFINEX <<< [678632,[37910,3,0.00379537]].
02/05 13:23:19.836914 DEBUG BITFINEX <<< [678632,[37905,6,0.52683472]].
02/05 13:23:19.837311 DEBUG BITFINEX <<< [678632,[37904,5,0.43354492]].
02/05 13:23:19.837717 DEBUG BITFINEX <<< [678632,[37829,5,0.00332517]].
02/05 13:23:19.838058 DEBUG BITFINEX <<< [678632,[37828,4,0.63181665]].
02/05 13:23:19.838341 DEBUG BITFINEX <<< [678632,[37936,1,-0.0931461]].
02/05 13:23:19.838582 DEBUG BITFINEX <<< [678632,"cs",-2128539290].
02/05 13:23:20.033430 DEBUG BITFINEX <<< [678632,[37952,0,-1]].
02/05 13:23:20.034097 DEBUG BITFINEX <<< [678632,[37931,7,2.02203508]].
02/05 13:23:20.034451 DEBUG BITFINEX <<< [678632,[37916,5,1.69867772]].
02/05 13:23:20.034734 DEBUG BITFINEX <<< [678632,[37909,5,0.13294561]].
02/05 13:23:20.034946 DEBUG BITFINEX <<< [678632,[37954,3,-0.65018022]].
02/05 13:23:20.035157 DEBUG BITFINEX <<< [678632,[37960,3,-0.58495452]].
02/05 13:23:20.035365 DEBUG BITFINEX <<< [678632,[37963,1,-0.30154917999999997]].
02/05 13:23:20.035544 DEBUG BITFINEX <<< [678632,[37993,4,-5.62858958]].
02/05 13:23:20.035716 DEBUG BITFINEX <<< [678632,[37994,2,-0.86579009]].
02/05 13:23:20.035866 DEBUG BITFINEX <<< [678632,"cs",-1150556826].
02/05 13:23:20.231820 DEBUG BITFINEX <<< [678632,[37936,0,-1]].
02/05 13:23:20.232392 DEBUG BITFINEX <<< [678632,[37941,0,-1]].
02/05 13:23:20.232607 DEBUG BITFINEX <<< [678632,[37950,0,-1]].
02/05 13:23:20.232803 DEBUG BITFINEX <<< [678632,[37931,8,2.82203508]].
02/05 13:23:20.233035 DEBUG BITFINEX <<< [678632,[37919,5,0.19887372]].
02/05 13:23:20.233222 DEBUG BITFINEX <<< [678632,[37915,6,1.47057072]].
02/05 13:23:20.233434 DEBUG BITFINEX <<< [678632,[37911,6,0.10419532]].
02/05 13:23:20.233664 DEBUG BITFINEX <<< [678632,[37910,2,0.00064172]].
02/05 13:23:20.233859 DEBUG BITFINEX <<< [678632,[37909,6,0.16448162]].
02/05 13:23:20.234045 DEBUG BITFINEX <<< [678632,[37908,6,1.57094172]].
02/05 13:23:20.234241 DEBUG BITFINEX <<< [678632,[37906,5,2.03807932]].
02/05 13:23:20.234411 DEBUG BITFINEX <<< [678632,[37905,7,0.58990675]].
02/05 13:23:20.234626 DEBUG BITFINEX <<< [678632,[37904,4,0.37047172]].
02/05 13:23:20.234811 DEBUG BITFINEX <<< [678632,[37901,8,25.27786254]].
02/05 13:23:20.234983 DEBUG BITFINEX <<< [678632,[37937,1,-0.09315889]].
02/05 13:23:20.235151 DEBUG BITFINEX <<< [678632,[37953,5,-1.5854378]].
02/05 13:23:20.235303 DEBUG BITFINEX <<< [678632,[37954,4,-1.04584422]].
02/05 13:23:20.235472 DEBUG BITFINEX <<< [678632,[37956,3,-1.44456779]].
02/05 13:23:20.235617 DEBUG BITFINEX <<< [678632,[37959,1,-0.125]].
02/05 13:23:20.235804 DEBUG BITFINEX <<< [678632,[37960,4,-0.95759008]].
02/05 13:23:20.235953 DEBUG BITFINEX <<< [678632,[38008,2,-0.00081464]].
02/05 13:23:20.236118 DEBUG BITFINEX <<< [678632,[38009,4,-0.62227931]].
02/05 13:23:20.236269 DEBUG BITFINEX <<< [678632,[38033,5,-5.93465368]].
02/05 13:23:20.236412 DEBUG BITFINEX <<< [678632,[38036,5,-0.25566218]].
02/05 13:23:20.236554 DEBUG BITFINEX <<< [678632,[38059,4,-0.02248249]].
02/05 13:23:20.236716 DEBUG BITFINEX <<< [678632,[38060,4,-0.00226851]].
02/05 13:23:20.236860 DEBUG BITFINEX <<< [678632,"cs",-2105777293].
02/05 13:23:20.369883 DEBUG BITFINEX <<< [0,"wu",["exchange","BTC",0.00112837,0,0.00112837,null,null]].
02/05 13:23:20.400302 DEBUG BITFINEX <<< [430687,"te",[600515848,1612531400275,-0.005,37931]].
02/05 13:23:20.436913 DEBUG BITFINEX <<< [678632,[37982,0,-1]].
02/05 13:23:20.437610 DEBUG BITFINEX <<< [678632,[38056,0,-1]].
02/05 13:23:20.437875 DEBUG BITFINEX <<< [678632,[38057,0,-1]].
02/05 13:23:20.438087 DEBUG BITFINEX <<< [678632,[38058,0,-1]].
02/05 13:23:20.438237 DEBUG BITFINEX <<< [678632,[38059,0,-1]].
02/05 13:23:20.438418 DEBUG BITFINEX <<< [678632,[38060,0,-1]].
02/05 13:23:20.438663 DEBUG BITFINEX <<< [678632,[37931,8,2.81703508]].
02/05 13:23:20.438844 DEBUG BITFINEX <<< [678632,[37903,10,0.80038486]].
02/05 13:23:20.438996 DEBUG BITFINEX <<< [678632,[37890,4,0.00104314]].
02/05 13:23:20.439167 DEBUG BITFINEX <<< [678632,[37870,6,0.19094277]].
02/05 13:23:20.439344 DEBUG BITFINEX <<< [678632,[37862,3,0.00084314]].
02/05 13:23:20.439538 DEBUG BITFINEX <<< [678632,[37851,7,26.98223435]].
```
if you still are unsure of the data pasted, just send it to analpaper@gmail.com and nobody else will see it sure

thank you'0¡ (meanwhile even if doesnt matter i can confirm im not having out of sync books here :S)

**Comment by ctubio** [comment]
okok what i most interested to know now is what currency pairs are you using :D (so i can try with the same)

:koala: thank you0'!

**Comment by MiningInMySleep** [comment]
E-mailed you the logs. Somehow got the error as I was logging. You can see it happen near line 6169. Only on btc/usd at the moment.

**Comment by ctubio** [comment]
:koala: i dont see nothing else wrong on bitfinex; lemme close this issue

**Comment by eniware-org** [comment]
Running with the latest version and this is happening again!

![image](https://user-images.githubusercontent.com/34030382/107864392-9cfb7c00-6e53-11eb-9c82-4da7b1909a92.png)

I notice that the QE is connected before the wallet and orders WS is OK. Manual disconnect/connect fixes it.
