### ISSUE TITLE
Recalculate safeties after trade, not only every second

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#313]
Hi everyone,

I come back after some extensive tests and I can say that PingPong mode is a bit broken.

I insist on PingPong because I believe it's the best strategy you can use with the bot.

So what I've seen not functioning correctly:
BuyPing / SellPing is not always updated. -> It should be updated at every trade even if it's just a 0.01 sell or buy, because a ping amount can value a lot!

The aggressive/fair setting is not working correctly:
Ping Width is not respected when using ShortPingAggressive -> ping width must be always respected.
Pong width should be respected from the FV only in short/long ping fair, as stated in the manual. :p 

BuyPing / SellPing is reset to 0 if price goes below BuyPing by ping width value (or price goes above sell ping by ping width value). It should be pong width value instead of ping width value!

Well again I come back on that because Pingpong is really important :p 

Best,

Camille

**Comment by Camille92** [comment]
PS: that might be just with % width ! So I'm running more test without the option.

**Comment by ctubio** [comment]
safeties are calculated every second, not after every trade, see https://github.com/ctubio/Krypto-trading-bot/blob/master/src/server/qe.h#L27

we can recalculate safeties after a trades too, but this is a new feature not the solution to a broken feature

about the zeroed values when price goes over or below, is because we intentionaly  reset to zero, to allow the bot continue trading and not to leave it stucked in a impossible price while the market moves far away ahead in the other direction

**Comment by ctubio** [comment]
hope you agree with the title, otherwise feel free to reedit it :dancer:

**Comment by ctubio** [comment]
oh well, that is already done, after a trade safeties are recalculated at https://github.com/ctubio/Krypto-trading-bot/blob/master/src/server/qe.h#L51

**Comment by Camille92** [comment]
Hey Carles,

I think it did not explain it correctly.
I know how ping-pong should work, but it's not working as expected today.

I'll come with a better and detailed explanation later today.

Best,
Camille

**Comment by Camille92** [comment]
Buy Ping and Pong Ping change in function of the width you put in, here is the real issue!

Ping pong should use last buy and last sold as a value and report it to get the price, as easy as that.
Not look through the history to find the best matching quote!

Like if I have a width ping of 0.2 and width pong of 0.5

I'm using short ping fair:
If I buy at 100, I want to sell at 100.5 only if width ping and width pong is respected from fair value.
If the price goes above 100.5 I'm selling like a Top with width 0.5.
If the price goes below 99.5, I'm selling like a top with a width 0.2.

Using short ping aggressive:
If I buy at 100, I want to sell at 100.5 but only if width ping is respected! (so FV = 100.4 max, if FV > 100.4, I sell like a normal top bot).
If the price goes below 99.5, I'm selling like a top with a width 0.2.


Now what's happening is so weird, it's just not working at all!

In theory, for each new trade the bot should update its buy ping and sell ping, but it's not doing it.

It's taking random number I can't figure out where they come from!

**Comment by Camille92** [comment]
Look in this example:
First I'm using a width ping and width pong of 0.5% width ShortPing Aggressive.
![capture d ecran 2017-10-20 a 12 16 39](https://user-images.githubusercontent.com/6861590/31816441-9ebc3b94-b590-11e7-99f5-86c4067a2683.png)
Look here, the Sell Ping should be 289.49  (the last sold) not 291.04.

Now if I change my width pong to 2%, it changed the sell ping to 295.77 instead of keeping the same and changing the objective.
![capture d ecran 2017-10-20 a 12 19 44](https://user-images.githubusercontent.com/6861590/31816558-17afca5c-b591-11e7-8486-6993df6fec12.png)

**Comment by ctubio** [comment]
all timers are new now; but i think it didnt help for this issue

**Comment by ctubio** [comment]
im looking at this, but just wanted to say that obviously buyping and sellping are not random values.
both walks through the list of historical trades accumulating the prices until meet the quantity of the next order, then normalizes the acumuluated prices to give a single price for the next order.

pongAt quoting parameter decides if the walk should start by the begining or by the end of the list of historical trades sorted by price.

**Comment by Camille92** [comment]
Hi Carles,

I'll update the bot and tell you how it's going.
I sure know it's not random but sometimes (actually most of the time if the bot has been running long enough) I can't find an order in history that matches it (that's why I call it random), because I search for an order that the bot would have chosen and can't find it!


Don't you think it would easier to create a new value "Last buy / last sold" (and maybe First buy/ first sold) to use rather than the trade history?

Thank you for having a look at the issue :)

**Comment by ctubio** [comment]
hope is fixed now (i did nothing just display asap the values in ther UI)

**Comment by Camille92** [comment]
Hi Carles,

The latest commits did not fix the problem.
I think another problem is the size of the trades to be considered the last one. Using % it can be complicated and create problems over time.
I'm in for an update of ping-pong that would not take into account buy and sell size and only consider the last buy and ping :)

**Comment by ctubio** [comment]
many thanks for propose a neat solution, will apply soOn''
