### ISSUE TITLE
hangs on bitfinex

### ISSUE THREAD

**Issue by hamedafra** [ctubio/Krypto-trading-bot#428]
Bot hangs on bitfinex after few minutes of working and debug mode also shows no error: 

<img width="968" alt="screen shot 2017-11-24 at 5 39 20 pm" src="https://user-images.githubusercontent.com/6717374/33214056-8a6693cc-d13f-11e7-8078-6f61c52de3fc.png">

It will be ok after I restart the bot

**Comment by donaldforest** [comment]
Same was on another server. I transfer bot to another clean server. Then looks bot works fine 24 hours on new. But I update it 2 days ago and then every mornong I found that bot UI not responsing, bot stop made orders, but completely answer in ssh console. I restart it now every morning.
Using: HitBTC.
Logl looks like yours. Nothing interested and last message in log is about get some trade data from exchange.. :(
Are You use --free-version?

**Comment by serzhiio** [comment]
Looks like you have big latency. I've expirienced something like that on bitfinex.

**Comment by donaldforest** [comment]
> ~/K$ ping api.hitbtc.com
PING api.hitbtc.com (165.227.244.237) 56(84) bytes of data.
64 bytes from 165.227.244.237: icmp_seq=1 ttl=58 time=97.4 ms
64 bytes from 165.227.244.237: icmp_seq=2 ttl=58 time=94.0 ms
64 bytes from 165.227.244.237: icmp_seq=3 ttl=58 time=94.2 ms
64 bytes from 165.227.244.237: icmp_seq=4 ttl=58 time=93.9 ms
64 bytes from 165.227.244.237: icmp_seq=5 ttl=58 time=95.6 ms
64 bytes from 165.227.244.237: icmp_seq=6 ttl=58 time=94.0 ms
^C
--- api.hitbtc.com ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5007ms
rtt min/avg/max/mdev = 93.965/94.914/97.436/1.270 ms

**Comment by hamedafra** [comment]
I tried both modes and there was no difference, I  also tried --headless mode and it worked a little more than the UI mode, but eventually it stoped working after a while

**Comment by donaldforest** [comment]
You using server OS? Clean or with lamp? Linux\Unix\Windows?

**Comment by hamedafra** [comment]
Clean Debian, on redstation

**Comment by donaldforest** [comment]
I using Ubuntu 16. If this will continue, I ask my admins to trace error. If get some result, Il reply this ticket.

**Comment by ctubio** [comment]
what means hangs? the UI is not responsive or it is responsive but with a red background? or is green background but not placing new orders?

**Comment by donaldforest** [comment]
In my case: No K in linux top PIDs. Console app don't quit by "q" (non naked mode). Just Ctrl+c - exit from console app. Web UI not response.

**Comment by adirta** [comment]
I have this problem. Since some update a week ago, approximately

**Comment by lunnh** [comment]
I have the same problem. I kept downgrading back until 610abb6 and it's running normally.

**Comment by donaldforest** [comment]
Updated yesterday.
Switched update and directory rights from root to standard user.
12 hours uptime and continue working ok. Testing..

**Comment by malt001** [comment]
Updated today to latest version. Still freezes after a few minutes on Ubuntu and HitBTC

**Comment by YokiWorks** [comment]
Same here, freezing on ubuntu with hitbtc and bitfinex

**Comment by SpencerMKSmith** [comment]
I am getting this same issue but with a different exchange.  I've tried on multiple versions of Ubuntu and Debian and I get the same freezing after a couple of minutes.

@donaldforest is it still running well for you after making that change?  Would you mind giving the exact permissions that you used and changes you made to get it running?

**Comment by YokiWorks** [comment]
@SpencerMKSmith @ctubio 
also tried on multiple machines and also with docker, after minute or two the process hangs on:
strace: Process 3652 attached
futex(0x55844b12eb50, FUTEX_WAIT_PRIVATE, 2, NULL

**Comment by SpencerMKSmith** [comment]
@lunnh How did you downgrade?  When I checkout that commit and `make install` I get errors.

@ctubio This issue is reproducible as many of us have encountered it, please consider changing the tag on the issue.

@YokiWorks Looks like a SQLite issue to me.  @donaldforest mentioned he was able to get it running by playing with some of the permissions to /data/db, but I was unable to get it to work in that way.

**Comment by lunnh** [comment]
@SpencerMKSmith I started noticing the bot hangs since some updates last week. Tried debug mode but found nothing. Thought it's my machine's own problem so I tried downgrading to older commits. The binary files for that commit was still available at that moment.

**Comment by YokiWorks** [comment]
@lunnh can you shoot me this binary pls? you would love to switch it in place the current one to see if it takes the problem away

**Comment by ctubio** [comment]
on Debian im not able to reproduce this yet; but this issue was opened 5 days before the last sqlite change (https://github.com/ctubio/Krypto-trading-bot/commit/1828232796098b358c8f9b944f6df6b74f917799#diff-533b8e08b8f13c06e18b929d8270fe24) so im afraid rolling it back will not help

can you share your `$ uname -a`? or better a link to an image of your very same distro? cos i would like to be able to reproduce it :dancer:

**Comment by lunnh** [comment]
@YokiWorks Here you go.
[build-x86_64-linux-gnu-610abb6.tar.gz](https://github.com/ctubio/Krypto-trading-bot/files/1516485/build-x86_64-linux-gnu-610abb6.tar.gz)

**Comment by gladstonedigital** [comment]
I'm having the same issue on Debian with gdax. It runs fine for the first few minutes, places a few trades, then the web UI stops updating (I can still click things but there's no new market data coming in) and even Ctrl+C on the command line doesn't kill the program. It says some stuff about chuck norris (???) but doesn't quit until I Ctrl+\ to kill it.

**Comment by ctubio** [comment]
im not sure that the problem here was fixed even if latest commit improved bitfinex, feel free to open a new issue just with a link to this if you wanna still improve bitfinex integration (or other exchange  integration)

**Comment by adirta** [comment]
Updated lastest version... On hitbtc with ubuntu, continue still freezing after a few minutes

**Comment by donaldforest** [comment]
Fixed with full reinstall last clean ubuntu 16 and install only necessary clean build-essential after apt update..
